package waroeng;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author indra
 */
public class DetailPenjualanFrame extends javax.swing.JFrame {

    private String idPenjualan;
    private String waktuPenjualan;
    private DefaultTableModel tableModel;

    /**
     * Creates new form DetailPenjualanFrame
     */
    public DetailPenjualanFrame() {
        initComponents();
        tableModel = new DefaultTableModel();
        tableModel.addColumn("barang");
        tableModel.addColumn("jumlah");
        tableModel.addColumn("Total");
        barangPenjualanTable.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        barangPenjualanTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idPenjualanLabel = new javax.swing.JLabel();
        ubahButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        tutupButton = new javax.swing.JButton();
        waktuPenjualanLabel = new javax.swing.JLabel();

        setAlwaysOnTop(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        barangPenjualanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Bakwan",  new Integer(21),  new Integer(10500)},
                {"Lemper",  new Integer(3),  new Integer(3000)},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Barang", "Jumlah", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(barangPenjualanTable);

        jLabel2.setText("Waktu:");

        jLabel1.setText("ID Penjualan : ");

        ubahButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ubahButton.setText("Ubah");

        hapusButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        hapusButton.setText("Hapus");

        tutupButton.setText("Tutup");
        tutupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupButtonActionPerformed(evt);
            }
        });

        waktuPenjualanLabel.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tutupButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ubahButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hapusButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(idPenjualanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(waktuPenjualanLabel)))
                            .addGap(0, 229, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idPenjualanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(waktuPenjualanLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubahButton)
                    .addComponent(hapusButton)
                    .addComponent(tutupButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        loadData();
    }//GEN-LAST:event_formComponentShown

    private void tutupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_tutupButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailPenjualanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailPenjualanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailPenjualanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailPenjualanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new DetailPenjualanFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable barangPenjualanTable;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel idPenjualanLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tutupButton;
    private javax.swing.JButton ubahButton;
    private javax.swing.JLabel waktuPenjualanLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the idPenjualan
     */
    public String getIdPenjualan() {
        return idPenjualan;
    }

    /**
     * @param idPenjualan the idPenjualan to set
     */
    public void setIdPenjualan(String idPenjualan) {
        this.idPenjualan = idPenjualan;
        idPenjualanLabel.setText(idPenjualan);
    }

    /**
     * @author: Idola Fitria Wati 101100054
     */
    private void loadData() {
        try {
            Statement statement = DatabaseUtil.getConnection().createStatement();

            String query = "SELECT barangpenjualan.barang,"
                    + "barangpenjualan.jumlah AS Jumlah,"
                    + "(barang.hargajual * barangpenjualan.jumlah) AS Total "
                    + "FROM barangpenjualan, barang "
                    + "WHERE barangpenjualan.barang = barang.nama "
                    + "AND barangpenjualan.idPenjualan = " + idPenjualan;

            ResultSet resultset = statement.executeQuery(query);

            getTableModel().getDataVector().removeAllElements();
            while (resultset.next()) {
                Object[] cols = new Object[3];
                cols[0] = resultset.getString("barangpenjualan.barang");
                cols[1] = Integer.valueOf(resultset.getInt("Jumlah"));
                cols[2] = Integer.valueOf(resultset.getInt("Total"));

                getTableModel().addRow(cols);
            }
            getTableModel().fireTableDataChanged();
        } catch (SQLException ex) {
            Logger.getLogger(DetailPenjualanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @return the waktuPenjualan
     */
    public String getWaktuPenjualan() {
        return waktuPenjualan;
    }

    /**
     * @param waktuPenjualan the waktuPenjualan to set
     */
    public void setWaktuPenjualan(String waktuPenjualan) {
        this.waktuPenjualan = waktuPenjualan;
        waktuPenjualanLabel.setText(waktuPenjualan);
    }

    /**
     * @return the tableModel
     */
    public DefaultTableModel getTableModel() {
        return tableModel;
    }

    /**
     * @param tableModel the tableModel to set
     */
    public void setTableModel(DefaultTableModel tableModel) {
        this.tableModel = tableModel;
    }
}
